name: Artifacts ci
on: [push]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Build project
       run: |
         mkdir -p output
         echo "hello" > output/artifact.txt
         ls -l output/
         cat output/artifact.txt
     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
         name: My-artifact
         path: output/
  download:
   needs: build
   runs-on: ubuntu-latest
   steps:
     - name: Download artifact
       uses: actions/download-artifact@v4
       with:
         name: My-artifact
         path: downloaded-artifact
     - name: Display content
       run: |
         ls -l downloaded-artifact/
         cat downloaded-artifact/artifact.txt
  
